# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK v11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      
      #- name: Package with maven
       # run: mvn clean install

      - name: Setup Java JDK v8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      
      - name: Download ShiftLeft CLI
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

      - name: preZero Static Analysis
        run: |
          ${GITHUB_WORKSPACE}/sl --version
          ${GITHUB_WORKSPACE}/sl analyze --strict --wait
            --app LaBrea \
            --verbose \
            --tag branch=${{ github.head_ref }} \
            --javasrc .
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          SHIFTLEFT_API_HOST: www.shiftleft.io
          SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
          SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

  Build-Rules:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: NextGen-Static-Analysis
    steps:
      - uses: actions/checkout@v3
      - name: Download ShiftLeft CLI
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
      - name: Validate Build Rules
        run: |
          ${GITHUB_WORKSPACE}/sl check-analysis --app LaBrea \
              --github-pr-number=${{github.event.number}} \
              --github-pr-user=${{ github.repository_owner }} \
              --github-pr-repo=${{ github.event.repository.name }} \
              --github-token=${{ secrets.GITHUB_TOKEN }}
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          SHIFTLEFT_API_HOST: www.shiftleft.io
          SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
          SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

      - name: Download bestfix script
        run: |
          python3 -m pip install --upgrade pip
          git clone https://github.com/ShiftleftSecurity/field-integrations.git
          pip3 install -r field-integrations/shiftleft-utils/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run bestfix script to generate report
        run: |
          python3 field-integrations/shiftleft-utils/bestfix.py -a ${{ github.repository }} -o $HOME/ngsast-bestfix-report.html
        working-directory: ${{ github.workspace }}
      
      - name: Post Analysis Report to PR
        run: |
          CHECK_ANALYSIS_OUTPUT=$(<ngsast-bestfix-report.html)
          body=$( jq -n --arg body "$CHECK_ANALYSIS_OUTPUT" '{ "body": $body }' )
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$body" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.number }}/comments"
